/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#14281D",
        "primary-container": "#1B3828",
        "secondary": "#2D5A40",
        "secondary-variant": "#3E7B57",
        "sage-tint": "#E8F0EB",
        "tertiary-accent": "#C86D44",
        "canvas": "#FBF9F5",
        "surface": "#FFFFFF",
        "surface-cream": "#F4EFE6",
        "hairline": "#EAE3D6",
        "hairline-variant": "#E5DFD5",
        "ink-primary": "#1C201D",
        "ink-secondary": "#4A554D",
        "ink-muted": "#7A877E",
        "background": "#FBF9F5",
        "foreground": "#1C201D",
      },
      fontFamily: {
        "newsreader": ["Newsreader", "serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "margin-sm": "1rem",
        "margin": "2rem",
      },
      boxShadow: {
        "level-1": "0px 2px 8px -2px rgba(20, 40, 29, 0.04), 0px 1px 3px 0px rgba(20, 40, 29, 0.02)",
        "level-2": "0px 12px 28px -6px rgba(20, 40, 29, 0.07), 0px 4px 10px -2px rgba(20, 40, 29, 0.03)",
        "level-3": "0px 24px 48px -12px rgba(20, 40, 29, 0.14)",
      }
    },
  },
  plugins: [],
};
