/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e9e4",
        "surface-container-low": "#f1f4ef",
        "secondary-fixed": "#bceecc",
        "primary": "#011209",
        "surface-tint": "#4e6356",
        "surface": "#f7faf5",
        "inverse-primary": "#b5ccbc",
        "surface-bright": "#f7faf5",
        "on-error-container": "#93000a",
        "surface-container": "#ecefea",
        "outline": "#737873",
        "on-surface-variant": "#424844",
        "secondary-fixed-dim": "#a1d2b1",
        "secondary": "#3a684d",
        "on-primary": "#ffffff",
        "outline-variant": "#c2c8c2",
        "on-primary-container": "#7a9081",
        "surface-dim": "#d8dbd6",
        "inverse-surface": "#2d312e",
        "tertiary-fixed-dim": "#ffb597",
        "on-tertiary-fixed-variant": "#79310c",
        "on-secondary-fixed": "#002111",
        "on-tertiary-container": "#cf7249",
        "on-primary-fixed": "#0b1f15",
        "inverse-on-surface": "#eff2ec",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#374b3f",
        "on-background": "#191d1a",
        "surface-variant": "#e0e3de",
        "tertiary": "#210600",
        "background": "#f7faf5",
        "tertiary-fixed": "#ffdbcd",
        "primary-container": "#14281d",
        "primary-fixed-dim": "#b5ccbc",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d0e8d7",
        "error": "#ba1a1a",
        "on-surface": "#191d1a",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#224f36",
        "on-secondary-container": "#3f6c51",
        "tertiary-container": "#441500",
        "surface-container-highest": "#e0e3de",
        "secondary-container": "#b9ebc9",
        "on-tertiary-fixed": "#360f00",
        "sage-tint": "#e8f0eb",
        "tertiary-accent": "#c86d44"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "margin-sm": "1rem",
        "margin": "2rem"
      },
      fontFamily: {
        "newsreader": ["Newsreader", "serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Newsreader", "serif"],
        "display-lg-mobile": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }]
      },
      boxShadow: {
        "level-1": "0px 2px 8px -2px rgba(20, 40, 29, 0.04), 0px 1px 3px 0px rgba(20, 40, 29, 0.02)",
        "level-2": "0px 12px 28px -6px rgba(20, 40, 29, 0.07), 0px 4px 10px -2px rgba(20, 40, 29, 0.03)",
        "level-3": "0px 24px 48px -12px rgba(20, 40, 29, 0.14)"
      }
    },
  },
  plugins: [],
};
