/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8faf6",
        "surface-dim": "#d9dad7",
        "surface-bright": "#f8faf6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f0",
        "surface-container": "#edeeeb",
        "surface-container-high": "#e7e9e5",
        "surface-container-highest": "#e1e3df",
        "on-surface": "#191c1a",
        "on-surface-variant": "#414844",
        "inverse-surface": "#2e312f",
        "inverse-on-surface": "#f0f1ed",
        "outline": "#727973",
        "outline-variant": "#c1c8c2",
        "surface-tint": "#436653",
        "primary": "#002517",
        "on-primary": "#ffffff",
        "primary-container": "#183b2b",
        "on-primary-container": "#80a690",
        "inverse-primary": "#a9cfb9",
        "secondary": "#58605c",
        "on-secondary": "#ffffff",
        "secondary-container": "#d7dfda",
        "on-secondary-container": "#5b635f",
        "tertiary": "#381500",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#592600",
        "on-tertiary-container": "#e88341",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#c4ecd4",
        "primary-fixed-dim": "#a9cfb9",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#2b4e3d",
        "secondary-fixed": "#dce4df",
        "secondary-fixed-dim": "#c0c8c4",
        "on-secondary-fixed": "#161d1a",
        "on-secondary-fixed-variant": "#414845",
        "tertiary-fixed": "#ffdbc9",
        "tertiary-fixed-dim": "#ffb68c",
        "on-tertiary-fixed": "#321200",
        "on-tertiary-fixed-variant": "#753400",
        "background": "#f8faf6",
        "on-background": "#191c1a",
        "surface-variant": "#e1e3df",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "margin-sm": "1.25rem",
        "margin": "2.5rem",
      },
      fontFamily: {
        "hanken": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
