/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e9e5",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#414845",
        "secondary-fixed": "#dce4df",
        "on-surface-variant": "#414844",
        "inverse-primary": "#a9cfb9",
        "on-primary": "#ffffff",
        "primary-container": "#183b2b",
        "primary-fixed-dim": "#a9cfb9",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8faf6",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d7dfda",
        "surface-container-low": "#f3f4f0",
        "outline-variant": "#c1c8c2",
        "on-primary-container": "#80a690",
        "on-tertiary-fixed": "#321200",
        "on-error-container": "#93000a",
        "on-surface": "#191c1a",
        "outline": "#727973",
        "surface-tint": "#436653",
        "on-tertiary-fixed-variant": "#753400",
        "inverse-surface": "#2e312f",
        "error": "#ba1a1a",
        "primary-fixed": "#c4ecd4",
        "tertiary-container": "#592600",
        "tertiary-fixed": "#ffdbc9",
        "on-error": "#ffffff",
        "surface-variant": "#e1e3df",
        "primary": "#002517",
        "error-container": "#ffdad6",
        "surface-container": "#edeeeb",
        "tertiary-fixed-dim": "#ffb68c",
        "tertiary": "#381500",
        "on-secondary-fixed": "#161d1a",
        "on-background": "#191c1a",
        "inverse-on-surface": "#f0f1ed",
        "background": "#f8faf6",
        "on-primary-fixed-variant": "#2b4e3d",
        "surface-dim": "#d9dad7",
        "on-secondary-container": "#5b635f",
        "secondary": "#58605c",
        "secondary-fixed-dim": "#c0c8c4",
        "on-tertiary-container": "#e88341",
        "on-primary-fixed": "#002113",
        "surface-container-highest": "#e1e3df",
        "surface": "#f8faf6"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "margin-sm": "1.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "gutter-sm": "1rem",
        "margin": "2.5rem"
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "title-md": ["1.125rem", { lineHeight: "1.625rem", letterSpacing: "-0.005em", fontWeight: "500" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.03em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
